
server:  port: 8080
spring:  datasource:    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/testapi_db
    username: postgres
    password: root
  
  jpa:    properties:      hibernate:
        jdbc:
          lob:
            non_contextual_creation:true    show-sql: true
    hibernate:      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect  
  jackson:    serialization: 
      fail-on-empty-beans: false        
    